### ISSUE TITLE
Request textDocument/documentSymbol failed

### ISSUE THREAD

**Issue by Dragonisser** [Sarrus1/sourcepawn-studio#330]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest

# Further Information

Error below keeps popping up from time to time

Afterwards i cant ctrl+leftclick on functions to jump to its declaration
I need to restart the sourcepawn-lsp server to make it work again

# To Reproduce

1. Open project
2. Write code
3. Wait patiently for the error
4. Error

# Code to reproduce the behaviour

https://github.com/tf2td/towerdefense

# Expected behaviour

No error

# Error messages

```
[2023-08-09T21:00:12.986Z INFO] Telemetry is enabled. To disable it, use the --disable-telemetry flag.
[2023-08-09T21:00:12.987Z INFO] Starting sourcepawn-lsp version 0.10.19
[2023-08-09T21:00:14.577Z INFO] Received config [
    Object {
        "disableSyntaxLinter": Bool(false),
        "includesDirectories": Array [],
        "linterArguments": Array [],
        "mainPath": String("c:\\Users\\Dragonisser\\vscode\\towerdefense\\addons\\sourcemod\\scripting\\towerdefense.sp"),
        "spcompPath": String("E:\\sourcemod-1.11.0-git6936-windows\\addons\\sourcemod\\scripting\\spcomp.exe"),
    },
]
[2023-08-09T21:00:15.406Z INFO] Scanned all the files in 828.76ms:
    - 108 file(s) were scanned.
    - Parsing took 557.04ms.
    - Analysis took 271.72ms.
        - Analysis took 256.77ms.
        - Getting all items 14.95ms.
            - Getting includes took 3.43ms.
            - Cloning items took 11.52ms.
        
[Error - 11:00:15 PM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at n.validate (c:\Users\Dragonisser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:16862)
	at new n (c:\Users\Dragonisser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:17157)
	at ye (c:\Users\Dragonisser\.vscode\extensions\sarrus.sourcepawn-vscode-5.5.5-win32-x64\dist\spIndex.js:430:73787)
	at ye (c:\Users\Dragonisser\.vscode\extensions\sarrus.sourcepawn-vscode-5.5.5-win32-x64\dist\spIndex.js:430:73968)
	at o (c:\Users\Dragonisser\.vscode\extensions\sarrus.sourcepawn-vscode-5.5.5-win32-x64\dist\spIndex.js:430:48842)
	at Object.Kse [as map] (c:\Users\Dragonisser\.vscode\extensions\sarrus.sourcepawn-vscode-5.5.5-win32-x64\dist\spIndex.js:430:48928)
	at Object.wr [as asDocumentSymbols] (c:\Users\Dragonisser\.vscode\extensions\sarrus.sourcepawn-vscode-5.5.5-win32-x64\dist\spIndex.js:430:73754)
	at c (c:\Users\Dragonisser\.vscode\extensions\sarrus.sourcepawn-vscode-5.5.5-win32-x64\dist\spIndex.js:434:56081)
	at async n.provideDocumentSymbols (c:\Users\Dragonisser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:37143)

```

**Comment by Sarrus1** [comment]
Are you able to reproduce this in the latest versions?

**Comment by Dragonisser** [comment]
I haven't encountered it yet, tho i wasn't really using it either lately. If i run into it again ill let you know.

**Comment by Dragonisser** [comment]
Still happens:

```
[2023-10-10T11:55:21.977Z WARN] Unknown notification: textDocument/didSave
[2023-10-10T11:55:26.594Z WARN] Unknown notification: textDocument/didSave
[2023-10-10T11:55:29.461Z WARN] Unknown notification: textDocument/didSave
[Error - 1:55:42 PM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at r.validate (c:\Users\acks\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:121:16990)
	at new r (c:\Users\acks\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:121:17285)
	at ye (c:\Users\acks\.vscode\extensions\sarrus.sourcepawn-vscode-6.1.0-win32-x64\dist\spIndex.js:34:73456)
	at ye (c:\Users\acks\.vscode\extensions\sarrus.sourcepawn-vscode-6.1.0-win32-x64\dist\spIndex.js:34:73637)
	at o (c:\Users\acks\.vscode\extensions\sarrus.sourcepawn-vscode-6.1.0-win32-x64\dist\spIndex.js:34:48563)
	at Object.oj [as map] (c:\Users\acks\.vscode\extensions\sarrus.sourcepawn-vscode-6.1.0-win32-x64\dist\spIndex.js:34:48649)
	at Object.wr [as asDocumentSymbols] (c:\Users\acks\.vscode\extensions\sarrus.sourcepawn-vscode-6.1.0-win32-x64\dist\spIndex.js:34:73423)
	at c (c:\Users\acks\.vscode\extensions\sarrus.sourcepawn-vscode-6.1.0-win32-x64\dist\spIndex.js:38:56041)
	at async r.provideDocumentSymbols (c:\Users\acks\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:37581)
[2023-10-10T11:55:51.922Z WARN] Unknown notification: textDocument/didSave
[2023-10-10T11:55:53.431Z WARN] Unknown notification: textDocument/didSave
```

**Comment by Phil25** [comment]
It's happening consistently for me in the [TF2 RTD plugin](https://github.com/Phil25/RTD/), though its code is old and convoluted and I wasn't able to track it down to anything specific.

It only happens when you're editing the main `scripting/rtd.sp` file. If you go to `scripting/rtd/perks/drugged.sp` (or pretty much any other script file) then there aren't any issues.
```
[2023-11-01T03:31:22.950Z INFO] Telemetry is enabled. To disable it, use the --disable-telemetry flag.
[2023-11-01T03:31:22.951Z INFO] Starting sourcepawn-lsp version 0.12.0
[2023-11-01T03:31:22.957Z INFO] Received config [
    Object {
        "disableSyntaxLinter": Bool(false),
        "includesDirectories": Array [],
        "linterArguments": Array [],
        "mainPath": String("U:\\Work\\Code\\RTD\\scripting\\rtd.sp"),
        "spcompPath": String("U:\\Work\\Code\\RTD\\scripting\\spcomp.exe"),
    },
]
[2023-11-01T03:31:23.746Z ERROR] Unknown token: Range {
    start: Position {
        line: 206,
        character: 54,
    },
    end: Position {
        line: 206,
        character: 55,
    },
}
[2023-11-01T03:31:23.832Z ERROR] Unknown token: Range {
    start: Position {
        line: 206,
        character: 54,
    },
    end: Position {
        line: 206,
        character: 55,
    },
}
[2023-11-01T03:31:24.014Z ERROR] Unknown token: Range {
    start: Position {
        line: 206,
        character: 54,
    },
    end: Position {
        line: 206,
        character: 55,
    },
}
[2023-11-01T03:31:24.164Z WARN] Unknown notification: $/setTrace
[2023-11-01T03:31:24.164Z WARN] Unknown notification: $/setTrace
[2023-11-01T03:31:24.164Z WARN] Unknown notification: $/setTrace
[2023-11-01T03:31:24.520Z WARN] Unknown notification: $/setTrace
[2023-11-01T03:31:24.520Z WARN] Unknown notification: $/setTrace
[2023-11-01T03:31:24.520Z WARN] Unknown notification: $/setTrace
[Error - 4:31:24 AM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at r.validate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:121:16990)
	at new r (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:121:17285)
	at ye (c:\Users\phil\.vscode\extensions\sarrus.sourcepawn-vscode-6.2.0-win32-x64\dist\spIndex.js:34:73456)
	at ye (c:\Users\phil\.vscode\extensions\sarrus.sourcepawn-vscode-6.2.0-win32-x64\dist\spIndex.js:34:73637)
	at o (c:\Users\phil\.vscode\extensions\sarrus.sourcepawn-vscode-6.2.0-win32-x64\dist\spIndex.js:34:48563)
	at Object.oj [as map] (c:\Users\phil\.vscode\extensions\sarrus.sourcepawn-vscode-6.2.0-win32-x64\dist\spIndex.js:34:48649)
	at Object.wr [as asDocumentSymbols] (c:\Users\phil\.vscode\extensions\sarrus.sourcepawn-vscode-6.2.0-win32-x64\dist\spIndex.js:34:73423)
	at c (c:\Users\phil\.vscode\extensions\sarrus.sourcepawn-vscode-6.2.0-win32-x64\dist\spIndex.js:38:56041)
	at async r.provideDocumentSymbols (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:37581)
```

**Comment by Sarrus1** [comment]
Thanks for the details, will look into that!

**Comment by Dragonisser** [comment]
In my case its with this plugin, but i couldnt narrow it down. https://github.com/tf2td/towerdefense

**Comment by Toyguna** [comment]
I have the same problem as well, what I have reproduced the bug. The bug only occurs when an EMPTY enum exists in a file, doesn't matter if an inc file or an sp file.

```php

enum Test
{
   // This will result in "Request textDocument/documentSymbol failed."
   // L Error: name must not be falsy
}

```

However this will not:
```php

enum Test
{
   TEST_ENUM1
}

However none of the files the OP and others commented on have empty enums in them, I guess I just encountered another producer of the bug.

( Also autocompletion seems to be broken in .inc files but that is another issue for another day :) )
```

**Comment by Classes123** [comment]
the same error occurs when the extension tries to show an overview of the function, idk, maybe it's somehow related to enums.

```cpp
enum UITaskMessage_Color {
    UITaskMessage_Fail,
    UITaskMessage_Success
}

void UITaskMessage_Display(WCPlayer pl, UITaskMessage_Color color, )
{
    
}
```

![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/64929923/90e24a62-cdc7-4bda-b862-553c73d652d9)


```
[Error - 11:43:06 PM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at d.validate (c:\Users\*\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:137:17256)
	at new d (c:\Users\*\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:137:17551)
	at ye (c:\Users\*\.vscode\extensions\sarrus.sourcepawn-vscode-6.2.0-win32-x64\dist\spIndex.js:34:73456)
	at ye (c:\Users\*\.vscode\extensions\sarrus.sourcepawn-vscode-6.2.0-win32-x64\dist\spIndex.js:34:73637)
	at o (c:\Users\*\.vscode\extensions\sarrus.sourcepawn-vscode-6.2.0-win32-x64\dist\spIndex.js:34:48563)
	at Object.oj [as map] (c:\Users\*\.vscode\extensions\sarrus.sourcepawn-vscode-6.2.0-win32-x64\dist\spIndex.js:34:48649)
	at Object.wr [as asDocumentSymbols] (c:\Users\*\.vscode\extensions\sarrus.sourcepawn-vscode-6.2.0-win32-x64\dist\spIndex.js:34:73423)
	at c (c:\Users\*\.vscode\extensions\sarrus.sourcepawn-vscode-6.2.0-win32-x64\dist\spIndex.js:38:56041)
	at async d.provideDocumentSymbols (c:\Users\*\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:39616)
```

```Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044
```

Extension version: v6.2.0

**Comment by Dragonisser** [comment]
Sadly its still happening and i have no idea why.

**Comment by stas11s11t** [comment]
This is terrible, I just type "char" and this window immediately pops up and even the AI ​​can’t help turn off this annoying window. It's strange that there is no setting in VS Code to disable it. This is just spam that prevents you from writing code.

**Comment by Sarrus1** [comment]
I will look into this again, it seems like the empty enum name error is back.

**Comment by Sarrus1** [comment]
Seems like this has been fixed somehow? Closing this for now. Please reopen if this shows up again.

**Comment by xice1337** [comment]
I'm still getting this error:
```
[Error - 2:22:54 PM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
    at Gd.validate (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:109:33647)
    at new Gd (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:109:33936)
    at He (c:\Users\watti.vscode\extensions\sarrus.sourcepawn-vscode-8.0.6-win32-x64\dist\spIndex.js:33:73362)
    at He (c:\Users\watti.vscode\extensions\sarrus.sourcepawn-vscode-8.0.6-win32-x64\dist\spIndex.js:33:73543)
    at o (c:\Users\watti.vscode\extensions\sarrus.sourcepawn-vscode-8.0.6-win32-x64\dist\spIndex.js:33:48494)
    at Object.eq [as map] (c:\Users\watti.vscode\extensions\sarrus.sourcepawn-vscode-8.0.6-win32-x64\dist\spIndex.js:33:48580)
    at Object.Yr [as asDocumentSymbols] (c:\Users\watti.vscode\extensions\sarrus.sourcepawn-vscode-8.0.6-win32-x64\dist\spIndex.js:33:73329)
    at c (c:\Users\watti.vscode\extensions\sarrus.sourcepawn-vscode-8.0.6-win32-x64\dist\spIndex.js:37:56049)
    at async uI.provideDocumentSymbols (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:138:126457)
```
I'm using the latest VSCode version and sourcwpawn-studio extension. I also have a lot of anonymous enums as well.
